metadata:
  general_description: Biallelic SNVs called from 2,548 human samples across 26 populations from the 1000 Genomes Project, called directly against GRCh38
  vcf_doi: https://www.ebi.ac.uk/ena/browser/view/PRJEB30460
  vcf_reference_genome_doi: https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.39
  gff3_doi: https://www.ensembl.org/Homo_sapiens/Info/Index

datadir:  C:/Users/arumuham/Desktop/Vcf_data/VCFToPhylogenetic/data/

variants:
  zarr_dir: ALL.shapeit2_integrated_v1a.GRCh38.2018112.zarr
  sample_id_mapping_filename: 


gff3:
  reference_seq: GRCh38_latest_genomic.fna
  vcf_file: ALL.shapeit2_integrated_v1a.GRCh38.20181129.phased.vcf.gz
  filename: Homo_sapiens.GRCh38.109.chr.gff3
  additional_attributes_keys:  biotype,gene_id
  key_confidence: false
  key_ontology: Ontology_term
  feature_type_with_description: gene
  main_feature_types_for_genes_track:
    - gene
    - pseudogene
    - ncRNA_gene
  count_exon_variants: false
  external_link_ontology_term: 
  external_links:
    - feature_attribute: gene_id
      url: https://www.ensembl.org/Homo_sapiens/Gene/Summary?g={FEATURE_ID}
      linktext: Open this gene on ensembl.org


chromosome_labels:
  chr1: chr1
  chr2: chr2
  chr3: chr3



gff3_chromosome_labels:
  chr1: 1
  chr2: 2
  chr3: 3



centromeres_positions:
  chr1: 0
  chr2: 0
  chr3: 0


blast:
  active: false
  galaxy_server_url:
  galaxy_user:
  galaxy_pass:
  galaxy_tool_id:
  blast_database:
  blast_type: megablast
  blast_result_to_vcf_chromosome_mapping: